Implemented QIM Mvt Watermark & added unit test project
sam-is/mvt-watermarking pull request #6
Opened 2022-11-08 15:03 UTC by danlla

2022-11-08 16:40 UTC, kolyanch requested changes

2022-11-08 16:40 UTC, kolyanch commented on MvtWatermark/MvtWatermark/QimMvtWatermark/QimMvtWatermark.cs
> +                for (int j = 0; j < _options.M; j++)
var

2022-11-08 16:40 UTC, kolyanch commented on MvtWatermark/MvtWatermark/QimMvtWatermark/QimMvtWatermark.cs
> +            var count = 0;
What is the purpose of this variable?

2022-11-08 16:40 UTC, kolyanch commented on MvtWatermark/MvtWatermark/QimMvtWatermark/QimMvtWatermark.cs
> +        private double Statistics(VectorTile tile, Polygon polygon, bool[,] map, Envelope envelopeTile, double extentDist, out int s0, out int s1)
1. Nothing will change in this method if you replace Polygon with Geometry. Is it essential to use Polygon?
2. tileEnvelope sounds better than envelopeTile

2022-11-08 16:40 UTC, kolyanch commented on MvtWatermark/MvtWatermark/QimMvtWatermark/QimMvtWatermark.cs
> +            public int x;
1. X
2. readonly

2022-11-08 16:40 UTC, kolyanch commented on MvtWatermark/MvtWatermark/QimMvtWatermark/QimMvtWatermark.cs
> +            public int y;
1. Y
2. readonly

2022-11-08 16:40 UTC, kolyanch commented on MvtWatermark/MvtWatermark/QimMvtWatermark/QimMvtWatermark.cs
> +                if (Convert.ToInt32(map[x + 1, y]) != value)
There are a lot of conversions in the code.
Maybe it's better to make "map" variable a matrix of int's? or vice versa make "value" variable a bool?
It's the same in a bunch of other methods

2022-11-08 16:40 UTC, kolyanch commented on MvtWatermark/MvtWatermark/QimMvtWatermark/QimMvtWatermark.cs
> +        private List<IntPoint> GetOppositePoint(bool[,] map, int x, int y, int value)
IEnumerable<IntPoint>

2022-11-08 16:40 UTC, kolyanch commented on MvtWatermark/MvtWatermark/QimMvtWatermark/QimMvtWatermark.cs
> +        private List<IntPoint> FindOppositeIndexes(bool[,] map, int value, int x, int y)
Add empty line

2022-11-08 16:40 UTC, kolyanch commented on MvtWatermark/MvtWatermark/QimMvtWatermark/QimMvtWatermark.cs
> +                                    double yMeteres = envelopeTile.MinY + point.y * extentDist;
1. var
2. There is a mistake in the word Meteres

2022-11-08 16:40 UTC, kolyanch commented on MvtWatermark/MvtWatermark/QimMvtWatermark/QimMvtWatermark.cs
> +                                    var coor = CoordinateConverter.MetersToDegrees(new Coordinate(xMeteres, yMeteres));
Maybe "coord" is better?

2022-11-08 16:40 UTC, kolyanch commented on MvtWatermark/MvtWatermark/QimMvtWatermark/QimMvtWatermark.cs
> +                                    var tmp = 0;
This is a terrible name for a variable

2022-11-08 16:40 UTC, kolyanch commented on MvtWatermark/MvtWatermark/QimMvtWatermark/QimMvtWatermark.cs
> +                                        if (coordinate.X == coordinateMeters.X && coordinate.Y == coordinateMeters.Y)
Bad comparison.
Do it like that:
```C#
Math.Abs(coordinate.X - coordinateMeters.X) < tiny const number
```

Example: https://dotnetfiddle.net/Md5p5Q

2022-11-08 16:40 UTC, kolyanch commented on MvtWatermark/MvtWatermark/QimMvtWatermark/QimMvtWatermark.cs
> +                    if (stat == -1)
Same problem with double comparing as above

2022-11-08 16:40 UTC, kolyanch commented on MvtWatermark/MvtWatermark/QimMvtWatermark/QimMvtWatermark.cs
> +                    var stat = Statistics(tile, polygon, map, envelopeTile, extentDist, out int s0, out int s1);
var in out statement

2022-11-08 16:40 UTC, kolyanch commented on MvtWatermark/MvtWatermark/QimMvtWatermark/QimMvtWatermark.cs
> +                    if (stat == -1)
See the notes on the previous method

2022-11-08 16:40 UTC, kolyanch commented on MvtWatermark/MvtWatermark/QimMvtWatermark/QimMvtWatermark.cs
> +            int current = 0;
var

2022-11-08 16:40 UTC, kolyanch commented on MvtWatermark/MvtWatermark/QimMvtWatermark/QimMvtWatermark.cs
> +                throw new ArgumentOutOfRangeException();
What exactly is the out-of-range method argument here?
Either you specify a specific argument in the constructor parameters, or this type of exception is not very suitable

2022-11-08 16:40 UTC, kolyanch commented on MvtWatermark/MvtWatermark/QimMvtWatermark/QimMvtWatermarkOptions.cs
> +﻿using System;
Cleanup solution

2022-11-08 16:40 UTC, kolyanch commented on MvtWatermark/MvtWatermarkTests/MvtWatermarkTests.csproj
> +    <TargetFramework>net5.0</TargetFramework>
Let's migrate to net6 and enable nullable

2022-11-08 16:40 UTC, kolyanch commented on MvtWatermark/MvtWatermarkTests/QimMvtWatermarkTests.cs
> +            var path = Path.Combine(Directory.GetCurrentDirectory(), "stp.mbtiles");
How can a third-party developer find this file?

2022-11-08 16:40 UTC, kolyanch commented on MvtWatermark/MvtWatermarkTests/QimMvtWatermarkTests.cs
> +            var z = 10;
const int

2022-11-08 16:40 UTC, kolyanch commented on MvtWatermark/MvtWatermarkTests/QimMvtWatermarkTests.cs
> +            using var memoryStream = new MemoryStream(bytes);
Check bytes for null

2022-11-08 16:40 UTC, kolyanch commented on MvtWatermark/MvtWatermarkTests/QimMvtWatermarkTests.cs
> +            var message = new BitArray(new bool[] {true});
The word "bool" is not needed here

2022-11-11 09:50 UTC, vicanfed requested changes
Ещё нужно:

1. Реализовать второй метод извлечения - с группировкой по `winx`
2. Добавить описание назначений методов и параметров в комментариях в `QimMvtWatermark` и `QimMvtWatermarkOptions`.
3. `key` для VectorTile не должен быть равен `key` для `VectorTileTree`. Он должен генерироваться на основе ID тайла и родительского `key`.

2022-11-11 09:50 UTC, vicanfed commented on MvtWatermark/MvtWatermark/QimMvtWatermark/QimMvtWatermarkOptions.cs
> +    public class QimMvtWatermarkOptions
Add Nb
Add joint M, R, Nb initialization by (int?, int?, int?)
Add T1
Make Delta2 private, add Delta1, init them based on k

2022-11-11 09:50 UTC, vicanfed commented on MvtWatermark/MvtWatermark/QimMvtWatermark/QimMvtWatermark.cs
> +            var sizeMessage = (int)Math.Floor((double)_options.M * _options.M / _options.R);
Calc this value inside the Options class

2022-11-14 05:43 UTC, kolyanch requested changes

2022-11-14 05:43 UTC, kolyanch commented on MvtWatermark/MvtWatermark/QimMvtWatermark/QimMvtWatermark.cs
> +    /// Сhecks the nearest points for the opposite value
The first letter C in the word Checks is written in Russian

2022-11-14 05:43 UTC, kolyanch commented on MvtWatermark/MvtWatermark/QimMvtWatermark/QimMvtWatermark.cs
> +            };
Unnecessary semicolon

2022-11-14 05:43 UTC, kolyanch commented on MvtWatermark/MvtWatermark/QimMvtWatermark/QimMvtWatermark.cs
> +    /// <param name="tiles">Vector tile for embedding message</param>
*tile

2022-11-14 05:43 UTC, kolyanch commented on MvtWatermark/MvtWatermark/QimMvtWatermark/QimMvtWatermark.cs
> +    /// <param name="tiles">Vector tile to extract the message from</param>
*tile

2022-11-14 05:43 UTC, kolyanch commented on MvtWatermark/MvtWatermark/QimMvtWatermark/QimMvtWatermark.cs
> +    public VectorTile Embed(VectorTile tile, int key, BitArray message)
The return type should be nullable VectorTile

2022-11-14 05:43 UTC, kolyanch commented on MvtWatermark/MvtWatermark/QimMvtWatermark/QimMvtWatermark.cs
> +            return null!;
Null-forgiving operator is not needed if you return nullable

2022-11-14 05:43 UTC, kolyanch commented on MvtWatermark/MvtWatermark/QimMvtWatermark/QimMvtWatermark.cs
> +            return null!;
Null-forgiving operator is not needed if you return nullable

2022-11-14 05:43 UTC, kolyanch commented on MvtWatermark/MvtWatermark/QimMvtWatermark/QimMvtWatermark.cs
> +    public BitArray Extract(VectorTile tile, int key)
The return type should be nullable BitArray

2022-11-14 05:43 UTC, kolyanch commented on MvtWatermark/MvtWatermark/QimMvtWatermark/QimMvtWatermark.cs
> +    /// Extracts an embedded message from vectortiletree
*VectorTileTree

2022-11-14 05:43 UTC, kolyanch commented on MvtWatermark/MvtWatermarkTests/QimMvtWatermarkTests.cs
> +        var tiletree = new VectorTileTree();
*tileTree

2022-11-14 07:22 UTC, vicanfed requested changes

2022-11-14 07:22 UTC, vicanfed commented on MvtWatermark/MvtWatermark/QimMvtWatermark/QimMvtWatermarkOptions.cs
> +    }
Just set all the parameters and recall another constructor

2022-11-14 07:22 UTC, vicanfed commented on MvtWatermark/MvtWatermark/QimMvtWatermark/QimMvtWatermarkOptions.cs
> +    public QimMvtWatermarkOptions(double k, double t2, int t1, int extent, int distance,int nb, int r, bool isGeneralExtractionMethod = false)
Rewrite the constructor taking `int? nb, int? r, int? m` where this triplet is valid if the only value is null. In the implementation, check this condition and set the three properties calculating one missing value from two others.

2022-11-14 07:22 UTC, vicanfed commented on MvtWatermark/MvtWatermark/QimMvtWatermark/QimMvtWatermark.cs
> +                if (dict[i] > 0)
Majority voting is not implemented (see the final item in the description of the extraction procedure)

2022-11-23 16:05 UTC, merged