No distortion watermark oleg
sam-is/mvt-watermarking pull request #7
Opened 2022-11-23 12:06 UTC by EraserH

2022-11-25 08:43 UTC, vicanfed commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/NoDistortionWatermarkOptions.cs
> +    {
You should use more parameters: triplet (D, m, Nb), Ls, Lf (Lf is a new one - see the description), atypical encoding type, and a binary/enum flag signaling the use of linestrings' second half

2022-11-25 08:43 UTC, vicanfed commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/NoDistortionWatermark.cs
> +            } // нагенерили {Sk}
In future, {Sk} should be generated independently for each tile

2022-11-25 08:43 UTC, vicanfed commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/NoDistortionWatermark.cs
> +                int value;
Code duplication

2022-11-25 08:43 UTC, vicanfed commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/NoDistortionWatermark.cs
> +        public void EmbedAndWriteToFile(VectorTileTree tiles, int key, BitArray message)
Code duplication

2022-11-25 08:43 UTC, vicanfed commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/MapboxTileWriterWM.cs
> +                encoded[0] = GenerateCommandInteger(MapboxCommandType.MoveTo, 2);
Why 2?

2022-11-25 08:43 UTC, vicanfed commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/MapboxTileWriterWM.cs
> +                encoded.Add(GenerateParameterInteger(position.y));
And then MoveTo again to the second point of the geometry

2022-11-25 08:43 UTC, vicanfed commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/MapboxTileWriterWM.cs
> +            // если элементарный сегмент подходит, то встраиваем нетипичную конструкцию в первый реальный сегмент
Embed not in the first segment but in Ls random ones

2022-11-25 08:43 UTC, vicanfed commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/MapboxTileWriterWM.cs
> +                        lastLineToCommand = encodedIndex - 2; // отнимаем два параметра
maybe else after the bracket?

2022-11-25 08:43 UTC, vicanfed commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/MapboxTileWriterWM.cs
> +            {
Why do you process the first segment before the loop?

2022-11-25 08:43 UTC, vicanfed commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/MapboxTileWriterWM.cs
> +                    currentElementarySegment = currentRealSegment / realSegmentsInONEElemSegment; // тут ошибка: деление на ноль
All these simplifications should be removed in future releases.

2022-11-28 12:10 UTC, EraserH commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/NoDistortionWatermark.cs
> +        public void EmbedAndWriteToFile(VectorTileTree tiles, int key, BitArray message)
that's a test function, it will be deleted later

2023-02-01 14:02 UTC, kolyanch requested changes

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/DebugClasses/ConsoleWriter.cs
> +﻿using System;
Delete this file

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/DictionaryExtensions.cs
> +namespace NetTopologySuite.IO.VectorTiles.Mapbox
Wrong namespace

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/DictionaryExtensions.cs
> +{
Convert to file-scoped namespace without braces

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileReaderWM.cs
> +public class MapboxTileReaderWM
Naming violation

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileReaderWM.cs
> +    /// <param name="TileDict"></param>
Wrong param name
Describe this parameter

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileReaderWM.cs
> +    /// <param name="idAttributeName">Optional. Specifies the name of the attribute that the vector tile feature's ID should be stored in the NetTopologySuite Features AttributeTable.</param>
The method does not have these parameters

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileReaderWM.cs
> +            resultTree[tilePair.Key] = Read(tilePair.Value, tilePair.Key, null);
null!

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileReaderWM.cs
> +    public int? ExtractWM(Tile tile, ulong tileId, NoDistortionWatermarkOptions options, short firstHalfOfTheKey)
Naming violation

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileReaderWM.cs
> +    private int? ReadLineStringWM(NtsArtefacts.TileGeometryTransform tgs, IList<uint> geometry, NoDistortionWatermarkOptions options, int[] keySequence)
Naming violation

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileReaderWM.cs
> +        //int watermarkInt = -1;
Delete this line

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileReaderWM.cs
> +        return watermarkInt;
```C#
return options.AtypicalEncodingType switch
{
    NoDistortionWatermarkOptions.AtypicalEncodingTypes.MtLtLt => 
        ExtractWMFromSingleLinestringMtLtLt(tgs, geometry, ref currentIndex, ref currentX, ref currentY, options, keySequence),
    NoDistortionWatermarkOptions.AtypicalEncodingTypes.MtLtMt => 
        throw new NotImplementedException(),
    NoDistortionWatermarkOptions.AtypicalEncodingTypes.NLtCommands => 
        ExtractWMFromSingleLinestringNLt(tgs, geometry, ref currentIndex, ref currentX, ref currentY, options, keySequence),
    _ => null
};
```

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileReaderWM.cs
> +    private int? ExtractWMFromSingleLinestringMtLtLt(
Terrible name

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileReaderWM.cs
> +        NtsArtefacts.TileGeometryTransform tgs, IList<uint> geometry,
Parameter tgs is unused. Remove it

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileReaderWM.cs
> +        ref int currentIndex, ref int currentX, ref int currentY, NoDistortionWatermarkOptions options, int[] keySequence)
Change keySequence type to ```IReadOnlyList<int>```

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileReaderWM.cs
> +                else if (count < 2) // это условие, возможно, не нужно
Redundant 'else' word

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileReaderWM.cs
> +            var rNTGstart = false;
Naming violation

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileReaderWM.cs
> +                else
Remove 'else' word

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileReaderWM.cs
> +        var realSegmentsInONEElemSegment = realSegmentsNum / options.D;
Naming violation

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileReaderWM.cs
> +    private int? ExtractWMFromSingleLinestringNLt(
Naming violation

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileReaderWM.cs
> +        NtsArtefacts.TileGeometryTransform tgs, IList<uint> geometry,
Parameter tgs is unused. Remove it

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileReaderWM.cs
> +            }
```C#
realSegments.Add(!isFirstSegment);
```

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileReaderWM.cs
> +        var realSegmentsInONEElemSegment = realSegmentsNum / options.D;
Naming violation

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileReaderWM.cs
> +                extractedWatermarkInts = extractedWatermarkIntsSecondHalf;
Remove else word

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileWriterWM.cs
> +public static class MapboxTileWriterWM
Naming violation

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileWriterWM.cs
> +    private static bool _hasSuccessfullyEmbeded = false;
Remove initializer

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileWriterWM.cs
> +    /// <remarks>The "Embed" method in NoDistortionWatermark then transforms it into VectorTileTree</remarks>
Sync params with actual method parameters

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileWriterWM.cs
> +    public static Mapbox.Tile WriteWM(this VectorTile vectorTile, BitArray watermarkString, short firstHalfOfTheKey,
The same as above

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileWriterWM.cs
> +        var tgt = new NtsArtefacts.TileGeometryTransform(tile, extent);
Remove qualifier

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileWriterWM.cs
> +    /// <param name="stream"></param>
The method does not contain the stream parameter

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileWriterWM.cs
> +    private static IEnumerable<uint> Encode(IPuntal puntal, NtsArtefacts.TileGeometryTransform tgt)
Remove qualifier

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileWriterWM.cs
> +    private static IEnumerable<uint> Encode(ILineal lineal, NtsArtefacts.TileGeometryTransform tgt)
Remove qualifier

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileWriterWM.cs
> +    private static IEnumerable<uint> Encode(ILineal lineal, NtsArtefacts.TileGeometryTransform tgt, int watermarkInt,
Remove qualifier

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileWriterWM.cs
> +    /// <param name="KeySequence"></param>
Rename param

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileWriterWM.cs
> +    private static IEnumerable<uint> Encode(IPolygonal polygonal, NtsArtefacts.TileGeometryTransform tgt, int zoom)
Remove qualifier

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileWriterWM.cs
> +    private static IEnumerable<uint> EncodeWithWatermarkMtLtLt(CoordinateSequence sequence, NtsArtefacts.TileGeometryTransform tgt,
Remove qualifier

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileWriterWM.cs
> +        int lastLineToCommand; // индекс последнего LineTo CommandInteger
Join with assignment

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileWriterWM.cs
> +        ref int currentX, ref int currentY, int watermarkInt, NoDistortionWatermarkOptions options, int[] keySequence)
Replace int[] with ```IReadOnlyList<int>```

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileWriterWM.cs
> +                        }
```C#
encoded[lastCommand.Index] = lastCommand.Type switch
{
    Mapbox.MapboxCommandType.LineTo => GenerateCommandInteger(Mapbox.MapboxCommandType.MoveTo,
        1),
    Mapbox.MapboxCommandType.MoveTo => GenerateCommandInteger(Mapbox.MapboxCommandType.MoveTo,
        2),
    _ => encoded[lastCommand.Index]
};
```

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileWriterWM.cs
> +    private static IEnumerable<uint> EncodeWithWatermarkMtLtMt(CoordinateSequence sequence, NtsArtefacts.TileGeometryTransform tgt,
Remove qualifier

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileWriterWM.cs
> +    private static IEnumerable<uint> EncodeWithWatermarkNLt(CoordinateSequence sequence, NtsArtefacts.TileGeometryTransform tgt,
Remove qualifier

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileWriterWM.cs
> +        ref int currentX, ref int currentY, int watermarkInt, NoDistortionWatermarkOptions options, int[] keySequence)
Replace int[] with IReadOnlyList<int>

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileWriterWM.cs
> +        var currentElementarySegment = 0;
Declare this variable inside if block in cycle below

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileWriterWM.cs
> +    private static IEnumerable<uint> Encode(CoordinateSequence sequence, NtsArtefacts.TileGeometryTransform tgt,
Remove qualifier

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/SequenceGenerator.cs
> +    /// <param name="M"></param>
The method does not have these parameters

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/WatermarkTransform.cs
> +    /// <param name="B"></param>
The method does not have these parameters

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/NoDistortionWatermark.cs
> +    private NoDistortionWatermarkOptions _options;
readonly

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/NoDistortionWatermark.cs
> +        var readerWM = new MapboxTileReaderWM();
Naming violation

2023-02-01 14:02 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/NoDistortionWatermark.cs
> +        var readerWM = new MapboxTileReaderWM();
Naming violation

2023-02-02 10:12 UTC, kolyanch reviewed
Rename files: MapBox

2023-02-02 10:12 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileReaderWM.cs
> +    /// <param name="tileDict">Dictionary <ulong, Mapbox.Tile> that contains tile id as key and Mapbox vector tile as value</param>
Symbols < and > are prohibited in xml comments

2023-02-02 10:12 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/Auxiliary/MapboxTileWriterWM.cs
> +        NoDistortionWatermarkOptions options, int[] keySequence)
IReadOnlyList<int>

2023-02-02 10:12 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/NoDistortionWatermark.cs
> +        else if (message.Length == 1 && message[0] == false)
Remove else word

2023-02-02 10:12 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/NoDistortionWatermark.cs
> +            return new BitArray(new bool[] { false });
The type can be omitted:
```C#
return new BitArray(new[] { false }); 
```

2023-02-02 10:12 UTC, kolyanch commented on MvtWatermark/MvtWatermark/NoDistortionWatermark/NoDistortionWatermark.cs
> +        return new BitArray(new int[] { watermarkInts[0] });
Same here

2023-02-02 10:41 UTC, kolyanch approved these changes

2023-02-02 10:41 UTC, merged